# Konfigurasi dasar
theme: jekyll-theme-Cayman
title: GreenSortAI
description: GreenSortAI adalah aplikasi berbasis AI dan cloud yang membantu pengguna memilah sampah dengan benar, memberikan rekomendasi daur ulang, serta menghubungkan pengguna dengan bank sampah.

# Pengaturan build
markdown: kramdown
highlighter: rouge
permalink: pretty

# Pengaturan untuk test build
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

# Aktifkan mode verbose untuk debugging
verbose: true
