theme: jekyll-theme-Cayman
title: GreenSortAI
description: GreenSortAI adalah aplikasi berbasis AI dan cloud yang membantu pengguna memilah sampah dengan benar, memberikan rekomendasi daur ulang, serta menghubungkan pengguna dengan bank sampah.
